sudo: false

language: node_js

node_js:
  - '8'
  - '10'
  - 'node'

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'

cache:
  directories:
    - node_modules

install:
  - npm i -g npm@latest
  - npm install